"""Data models for slot state, abduction history, requirement cases, transcripts, and checkpoints."""

from typing import Literal
from pydantic import BaseModel, Field, field_validator


class Slot(BaseModel):
    """An explicit information slot tracking an elicitation target."""

    name: str = Field(description="Unique name or identifier for the slot.")
    category: str = Field(description="Category grouping for the requirement slot.")
    value: str | None = Field(default=None, description="Extracted requirement text or null if unfilled.")

    @field_validator("value", mode="before")
    @classmethod
    def normalize_value(cls, v: str | None) -> str | None:
        """Normalize empty strings or whitespace-only values to None."""
        if v is None:
            return None
        s = str(v).strip()
        return s if s else None

    @property
    def is_filled(self) -> bool:
        """Return True if the slot contains non-empty extracted text."""
        return self.value is not None and len(self.value.strip()) > 0


class AbductionRecord(BaseModel):
    """Record of an abductive reasoning step identifying a hypothesis and probing slot."""

    surprising_fact: str = Field(description="Observed surprising fact or unexpected constraint.")
    suspected_reason: str = Field(description="Hypothesized root cause or implicit requirement.")
    new_slot: str = Field(description="Name of the new slot introduced to probe the hypothesis.")


class RequirementCase(BaseModel):
    """Specification of a software requirement interview case."""

    case_id: str = Field(description="Unique identifier for the requirement case.")
    project_name: str = Field(description="Name of the software project under elicitation.")
    initial_requirements: str = Field(description="Initial requirements description and project context.")


class Message(BaseModel):
    """A single message exchanged within the LLM conversation context."""

    role: Literal["system", "user", "assistant"] = Field(description="Role of the message sender.")
    content: str = Field(description="Text content of the message.")


class DialogueTurn(BaseModel):
    """A single clean dialogue turn in the public conversation transcript."""

    turn_id: int = Field(description="1-based index of the dialogue turn.")
    interviewer_utterance: str = Field(description="Question or statement generated by the interviewer.")
    interviewee_utterance: str = Field(description="Answer provided by the stakeholder.")


class InterviewTurn(BaseModel):
    """An internal execution turn recording dialogue utterances and targeted slots."""

    turn_id: int = Field(description="1-based index of the dialogue turn.")
    interviewer_utterance: str = Field(description="Question or statement generated by the interviewer.")
    interviewee_utterance: str = Field(description="Answer provided by the stakeholder.")
    target_slots: list[str] = Field(
        default_factory=list,
        description="Target slots focused on during this interview turn.",
    )


class InterviewTranscript(BaseModel):
    """Clean public record of the conversation turns."""

    case_id: str = Field(description="Identifier of the elicited requirement case.")
    project_name: str = Field(description="Name of the software project.")
    turns: list[DialogueTurn] = Field(
        default_factory=list,
        description="Sequence of clean dialogue turns without internal state.",
    )


class InterviewCheckpoint(BaseModel):
    """Complete internal execution state for lossless session restoration."""

    case_id: str = Field(description="Identifier of the elicited requirement case.")
    project_name: str = Field(description="Name of the software project.")
    initial_requirements: str = Field(
        default="",
        description="Initial requirements text for complete context restoration.",
    )
    turns: list[InterviewTurn] = Field(
        default_factory=list,
        description="Sequence of completed interview execution turns.",
    )
    slots: list[Slot] = Field(
        default_factory=list,
        description="Final snapshot of all tracked slots and their extracted values.",
    )
    abduction_history: list[AbductionRecord] = Field(
        default_factory=list,
        description="Chronological record of abductive reasoning steps.",
    )
    pending_question: str | None = Field(
        default=None,
        description="Active interviewer question awaiting stakeholder response.",
    )
    pending_target_slots: list[str] = Field(
        default_factory=list,
        description="Target slots corresponding to the active pending question.",
    )
    is_finished: bool = Field(
        default=False,
        description="Flag indicating whether the interview has reached completion.",
    )
