"""Data models for requirement cases, dialogue messages, and interview transcripts."""

from typing import Literal
from pydantic import BaseModel, Field


class RequirementCase(BaseModel):
    """Specification of a software requirement interview case."""

    case_id: str = Field(description="Unique identifier for the requirement case.")
    project_name: str = Field(description="Name of the software project under elicitation.")
    initial_requirements: str = Field(description="Initial requirements description and project context.")


class Message(BaseModel):
    """A single message exchanged within the LLM conversation context."""

    role: Literal["system", "user", "assistant"] = Field(description="Role of the message sender.")
    content: str = Field(description="Text content of the message.")


class InterviewTurn(BaseModel):
    """A single completed question-answer turn in the interview session."""

    turn_id: int = Field(description="1-based index of the dialogue turn.")
    interviewer_utterance: str = Field(description="Question or statement generated by the interviewer.")
    interviewee_utterance: str = Field(description="Answer provided by the stakeholder.")


class InterviewTranscript(BaseModel):
    """Structured, self-contained record of an entire requirements interview session."""

    case_id: str = Field(description="Identifier of the elicited requirement case.")
    project_name: str = Field(description="Name of the software project.")
    initial_requirements: str = Field(
        default="",
        description="Initial requirements text for complete context restoration.",
    )
    turns: list[InterviewTurn] = Field(
        default_factory=list,
        description="Sequence of completed interview turns.",
    )
    pending_question: str | None = Field(
        default=None,
        description="Active interviewer question awaiting stakeholder response.",
    )
    is_finished: bool = Field(
        default=False,
        description="Flag indicating whether the interview has reached completion.",
    )
