"""Domain data models and schemas for RQ1 evaluation pipeline."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ManifestRecord(BaseModel):
    """Execution manifest recorded during interview execution."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    method_id: str
    project_name: str
    native_project_id: str
    method_model: str
    method_max_turns: int
    interviewee_model: str
    status: str
    completed_turns: int
    native_path: str
    finish_message: str | None = None
    error_message: str | None = None


class ConversationTurn(BaseModel):
    """Raw single turn in the interview conversation log."""

    model_config = ConfigDict(extra="forbid")

    turn_index: int
    role: str
    content: str


class TranscriptRecord(BaseModel):
    """Standardized record identifying an interview transcript."""

    model_config = ConfigDict(extra="forbid")

    transcript_id: str
    case_id: str
    method_id: str
    completed_turns: int


class ResponseRecord(BaseModel):
    """Single paired interviewer question and interviewee answer unit."""

    model_config = ConfigDict(extra="forbid")

    response_id: str
    transcript_id: str
    case_id: str
    method_id: str
    turn_index: int
    context_question: str
    answer: str


class ProposedRIU(BaseModel):
    """Requirement Information Unit fields generated by the language model."""

    model_config = ConfigDict(extra="forbid")

    ordinal: int
    statement: str
    evidence_start_segment_id: int
    evidence_end_segment_id: int


class ExtractedRIU(BaseModel):
    """Atomic Requirement Information Unit grounded in an interviewee answer."""

    model_config = ConfigDict(extra="forbid")

    ordinal: int
    statement: str
    evidence_text: str
    evidence_start: int
    evidence_end: int
    riu_id: str | None = None


class ExtractionOutput(BaseModel):
    """Raw model generation container for extraction task."""

    model_config = ConfigDict(extra="forbid")

    rius: list[ProposedRIU]


class ExtractionUnit(BaseModel):
    """Validated extraction result associated with a specific response."""

    model_config = ConfigDict(extra="forbid")

    response_id: str
    transcript_id: str
    case_id: str
    method_id: str
    turn_index: int
    rius: list[ExtractedRIU]


class DeduplicationGroup(BaseModel):
    """Group of semantically identical raw RIUs within one transcript."""

    model_config = ConfigDict(extra="forbid")

    representative_riu_id: str
    member_riu_ids: list[str]
    statement: str


class DeduplicationMatch(BaseModel):
    """Model-identified semantic identity between a new RIU and an earlier unit."""

    model_config = ConfigDict(extra="forbid")

    new_item_index: int
    target_type: Literal["existing_group", "new_item"]
    target_id: int


class DeduplicationOutput(BaseModel):
    """Sparse semantic identity relations generated for one deduplication batch."""

    model_config = ConfigDict(extra="forbid")

    duplicate_matches: list[DeduplicationMatch]


class RIUProvenance(BaseModel):
    """Tracing metadata pointing back to original turn and exact evidence."""

    model_config = ConfigDict(extra="forbid")

    riu_id: str
    response_id: str
    turn_index: int
    evidence_text: str
    evidence_start: int
    evidence_end: int
    context_question: str


class UniqueRIU(BaseModel):
    """Deduplicated canonical RIU within a single interview transcript."""

    model_config = ConfigDict(extra="forbid")

    transcript_riu_id: str
    transcript_id: str
    case_id: str
    method_id: str
    statement: str
    member_riu_ids: list[str]
    first_position: int
    provenance: list[RIUProvenance]


class DeduplicationUnit(BaseModel):
    """Checkpoint record for a completed transcript deduplication."""

    model_config = ConfigDict(extra="forbid")

    transcript_id: str
    case_id: str
    method_id: str
    groups: list[DeduplicationGroup]
    unique_rius: list[UniqueRIU]


class DeduplicationBatchUnit(BaseModel):
    """Checkpoint state after one completed transcript deduplication batch."""

    model_config = ConfigDict(extra="forbid")

    transcript_id: str
    case_id: str
    method_id: str
    processed_riu_count: int
    group_member_riu_ids: list[list[str]]


class EmbeddingIndexRecord(BaseModel):
    """Mapping entry associating embedding row index with unique RIU identifier."""

    model_config = ConfigDict(extra="forbid")

    row_index: int
    transcript_riu_id: str
    case_id: str
    statement: str


class ClusterAssignment(BaseModel):
    """Assignment of a unique RIU instance to a shared case-level cluster."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    transcript_riu_id: str
    transcript_id: str
    method_id: str
    cluster_id: str


class TranscriptClusterCoverage(BaseModel):
    """Transcript coverage over a specific shared requirement cluster."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    transcript_id: str
    method_id: str
    cluster_id: str
    transcript_riu_ids: list[str]


class BreadthMetricRecord(BaseModel):
    """Breadth metric evaluation record for a single transcript."""

    model_config = ConfigDict(extra="forbid")

    transcript_id: str
    case_id: str
    method_id: str
    breadth: int


class ElaborationNode(BaseModel):
    """Node definition within a transcript-cluster elaboration graph."""

    model_config = ConfigDict(extra="forbid")

    node_id: str
    turn_index: int
    evidence_start: int
    statement: str
    evidence_text: str
    context_question: str


class ElaborationPair(BaseModel):
    """Candidate directed pair evaluated for elaboration relation."""

    model_config = ConfigDict(extra="forbid")

    earlier_node_id: str
    later_node_id: str


class ElaborationDecision(BaseModel):
    """Model judgment for candidate node pair."""

    model_config = ConfigDict(extra="forbid")

    earlier_node_id: str
    later_node_id: str
    relation: Literal["elaboration", "none"]


class ElaborationSelection(BaseModel):
    """Unordered node pair selected by the model as an elaboration relation."""

    model_config = ConfigDict(extra="forbid")

    node_a_id: str
    node_b_id: str


class ElaborationOutput(BaseModel):
    """Raw model generation container for elaboration judgment."""

    model_config = ConfigDict(extra="forbid")

    elaboration_pairs: list[ElaborationSelection]


class ElaborationEdge(BaseModel):
    """Directed edge in an elaboration DAG from earlier node to later node."""

    model_config = ConfigDict(extra="forbid")

    source_id: str
    target_id: str


class ElaborationDAG(BaseModel):
    """Directed acyclic graph of requirement elaboration within one transcript and cluster."""

    model_config = ConfigDict(extra="forbid")

    transcript_id: str
    cluster_id: str
    nodes: list[ElaborationNode]
    edges: list[ElaborationEdge]


class DecisionUnit(BaseModel):
    """Checkpoint record for elaboration decisions within a composition unit."""

    model_config = ConfigDict(extra="forbid")

    transcript_id: str
    cluster_id: str
    decisions: list[ElaborationDecision]


class ClusterDepthRecord(BaseModel):
    """Depth metric calculation for a single transcript-cluster unit."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    transcript_id: str
    method_id: str
    cluster_id: str
    node_count: int
    edge_count: int
    depth: int


class TranscriptMetrics(BaseModel):
    """Primary evaluation metrics aggregated for an entire transcript."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    case_id: str
    transcript_id: str
    method_id: str
    yield_count: int = Field(..., alias="yield")
    breadth: int
    depth_counts: dict[str, int]


class RIUQualityAuditMetrics(BaseModel):
    """Quality metrics computed from single-reviewer RIU quality review annotations."""

    model_config = ConfigDict(extra="forbid")

    total_reviewed_rius: int
    evidence_faithfulness: float
    requirement_relevance: float
    segmentation_adequacy: float


class DeduplicationAuditMetrics(BaseModel):
    """Quality metrics computed from single-reviewer deduplication correctness review."""

    model_config = ConfigDict(extra="forbid")

    total_reviewed_groups: int
    deduplication_correctness: float | None = None


class OmissionAuditMetrics(BaseModel):
    """Summary of single-reviewer fast transcript-level omission screening."""

    model_config = ConfigDict(extra="forbid")

    total_reviewed_transcripts: int
    transcripts_with_major_omissions: int
    major_omission_rate: float
    has_major_omissions: bool


class AuditSummary(BaseModel):
    """Comprehensive summary container for human audit review results."""

    model_config = ConfigDict(extra="forbid")

    riu_quality: RIUQualityAuditMetrics
    deduplication: DeduplicationAuditMetrics
    omission: OmissionAuditMetrics
