slots:
  - name: "Career aspirations for next year"
    category: "Career"
    value: null
  - name: "Career development plan"
    category: "Career, Plan"
    value: null
  - name: "Future department preferences"
    category: "Career, Preference"
    value: null
  - name: "Career-related concerns"
    category: "Career, Concerns"
    value: null
  - name: "Training preferences"
    category: "Training, Preference"
    value: null
  - name: "Current job duties"
    category: "Job"
    value: null
  - name: "Job satisfaction"
    category: "Job, Satisfaction"
    value: null
  - name: "Job dissatisfaction"
    category: "Job, Dissatisfaction"
    value: null
